Mission4.1/Mission4.1/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission41.Models
{
    public class GradeCalcModel
    {
        //create attributes of the class for each input
       //Here we add a required range for the input 0 to 100 and if input does not meet requirements, an error message will let the user know
        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsAssign { get; set; } //the "{get; set;}" does everything that the below code does for you.

        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsGp { get; set; }

        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsQuiz { get; set; }

        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsMid { get; set; }

        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsFinal { get; set; }

        [Range(0, 100, ErrorMessage = "The percentages must be between 0 and 100")]
        public float ClsIntex { get; set; }
    }
}

Mission4.1/Mission4.1/Controllers/extraController.cs
using Microsoft.AspNetCore.Mvc;
using Mission41.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission41.Controllers
{
    public class extraController : Controller
    {
        public IActionResult Index()
        {
            return View();
            //if you do not put a parameter in the view() function, it will default to the index file
            //--this is because the index view is associated with this the iActionResult
        }
        [HttpGet]
        public IActionResult GradeCalc()
        {
            //this creates an action to go to the new GradeCalc View
            return View();
        }
        //add "object model to show that these are two diff methods
        [HttpPost] //attatch this attributes to the mehtod
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            //this creates an action to go to the new GradeCalc View
            return View();
        }
}
}

Mission4.1/Mission4.1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>

    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        @* here we will be getting the variable "Title" from the ViewData of each page, 
            so the title can be diff on each page *@
        <title>@ViewData["Title"]</title>
        <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/styles.css" rel="stylesheet" />
        <link rel="icon" type="image/x-icon" href="img/good-icon.webp" />
    </head>

    <body>

        <nav>
            @* This is the way to show paths of these diff views *@
            <a asp-controller="extra" asp-action="Index">Home</a>
            <a asp-controller="extra" asp-action="GradeCalc">Grade Calculator</a>
        </nav>

        <div>
            @RenderBody()
        </div>

        <script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>

    </body>

</html>

Mission4.1/Mission4.1/Views/extra/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator!!!";
}
@* Tell the program which model you are wanting to use *@
@model GradeCalcModel;

<h2>Grade Calculator</h2>
<h3>
    Please enter the grade percentage that you received <br />
    for each category of grading in this class.
</h3>

<form method="post">
  @* Inputs for grade percentages *@
    <label>Assignments</label><br />
    <input id="assign" asp-for="ClsAssign" type="number" /> % <br />
    <label>Group Project</label> <br />
    <input id="gp" asp-for="ClsGp" type="number" /> % <br />
    <label>Quizzes</label> <br />
    <input id="quiz" asp-for="ClsQuiz" type="number" /> %<br />
    <label>Midterm Exam</label><br />
    <input id="mid" asp-for="ClsMid" type="number" /> %<br />
    <label>Final Exam</label> <br />
    <input id="final" asp-for="ClsFinal" type="number" /> % <br />
    <label>INTEX</label><br />
    <input id="intex" asp-for="ClsIntex" type="number" /> % <br /><br />
    <input id="buttonCalc" type="submit" value="Calculate Grade" /> <br /><br />
    @* a label where the final letter grade message will be printed *@
    <label id="finalGrade"></label>

    <div asp-validation-summary="All"></div>
</form>

<script src="~/wwwroot/js/GradeCalc.js" type="text/javascript"></script>

Mission4.1/Mission4.1/Views/extra/index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@* Here the "Title" variable is being declared along with any other variable you want to make dynamic >>*@
@{
    ViewData["Title"] = "Maryn's Dreams";
}


<h1>Maryn</h1>
<p>This is me and my husband in the mountains freezing our tails off.</p>
<img src="img/DSC_5942.jpg" style="height: 300px">
<p>
    I hope to be more fluent in C# and ASP.NET <br />
    than any other language we have learned so far.<br />
    I have not put as much effort into learning Python <br />
    and JavaScript, but I want to repent by putting a <br />
    lot of effort into learning and practicing<br />
    the skills we learn in this class.
</p>
<h2>My Top 3 Job Picks</h2>
<ol>
    <li>Software Developer</li>
    <li>Database Engineer</li>
    <li>Cyber Security White Hat Hacker</li>
</ol>